/*

Transistor bridge , 4 pins

high A&C,low B,D 	= turnleft
high B&D,low A,C 	= turnleft
all low				= off
all high 			= look for a fire extinguisher!

++++++++++++++++++++++++++++
	A			 D
	|	______	 |
	---|   .  |--|
	|   ------	 |
	B    motor   C
------------------------------
*/



pin configuration:
	output motorA 1
	output motorB 2
	output motorC 3
	output motorD 4
 
aliases:
	alias motor (motorA motorB motorC motorD):
		state turnleft (high low low low)
		state turnright (low high low low)
		state off (low low low low)
	/*	no state defined for 4x high! */
	
repeat:
	switch motor turnleft
	wait 100ms
	switch motor off
	wait 100ms
	switch motor turnright
	wait 100ms
	switch motor off
	wait 100ms

	
	