pin configuration:
	output pin1 1
	output pin2 2
	output pin3 3
	output pin4 4
	output pin5 5

repeat:
	var x = 3
	if (4 > 3):
		set pin1 high
	if (3 < 4):
		set pin2 high
	if (4 == 4):
		set pin3 high
	if (4 >= 4):
		set pin4 high
	if (4 <= 4):
		set pin5 high
	if ((3+3)>7):
		set pin5 high		/* Unreachable */
	if (4 > x):
		set pin1 high
	if (3 < x):
		set pin2 high
	if (4 == x):
		set pin3 high
	if (4 >= x):
		set pin4 high
	if (4 <= x):
		set pin5 high
	if ((3+x)>x):
		set pin5 high