pin configuration:
	output pin2 2
	output pin3 3
	output pin4 4
	output pin5 5
	output pin6 6
	output pin7 7
	output pin8 8
	output pin9 9

do-once:
	for i from 2 to 8 step 1:
		set i high
	wait 2s


setdelay pin1 delay:
	set pin1 high
	wait delay
	set pin1 low
	
sweep_left:
	for i from 2 to 8 step 1:
		setdelay i 50ms
		

sweep_right:
	for i from 8 to 2 step -1:
		setdelay i 50ms	

repeat:
	sweep_left
	sweep_right
	var x = 5
