[
   Assignment                    -- _1 KW["="] _2,
   Assignment                    -- _1 KW["="] _2,
   Return                        -- KW["return"] _1,
   VarDecl                       -- KW["var"] _1,
   VarDecl                       -- KW["var"] _1 KW["="] _2,
   VarDecl                       -- KW["var"] _1,
   VarDecl                       -- KW["var"] _1 KW["="] _2,
   VarDecl                       -- KW["var"] _1 KW["="] _2,
   VarDecl                       -- _1,
   FuncCall                      -- _1 _2,
   FuncCall.2:iter               -- _1,
   If                            -- KW["if"] _1 KW[":"],
   Else                          -- KW["else"] KW[":"],
   While                         -- KW["while"] _1 KW[":"],
   For                           -- KW["for"] _1 KW["from"] _2 KW["to"] _3 KW[":"],
   For                           -- KW["for"] _1 KW["from"] _2 KW["to"] _3 KW["step"] _4 KW[":"],
   Print                         -- V  [H  [KW["print"]] _1],
   Print.1:iter-star-sep         -- _1 KW["++"],
   Extern                        -- KW["extern"] _1,
   String                        -- KW["\""] _1 KW["\""],
   FuncCallNoArgs                -- _1,
   Int                           -- _1,
   Plus                          -- _1 KW["+"] _2,
   Minus                         -- _1 KW["-"] _2,
   And                           -- _1 KW["&&"] _2,
   Or                            -- _1 KW["||"] _2,
   LT                            -- _1 KW["<"] _2,
   GT                            -- _1 KW[">"] _2,
   LTE                           -- _1 KW["<="] _2,
   GTE                           -- _1 KW[">="] _2,
   EQ                            -- _1 KW["=="] _2,
   NEQ                           -- _1 KW["!="] _2,
   Times                         -- _1 KW["*"] _2,
   Divide                        -- _1 KW["/"] _2,
   Bool                          -- _1,
   Not                           -- KW["!"] _1,
   Time                          -- _1,
   PWM                           -- _1 KW["%"],
   Program                       -- _1 _2 _3 _4 _5 _6,
   Program.1:iter-star           -- _1,
   Pinconfigurations             -- ,
   Aliases                       -- ,
   Externals                     -- ,
   Globals                       -- ,
   Pinconfigurations             -- V  [V vs=2 [KW["pin configuration:"] _1] _2],
   Pinconfigurations.1:iter-star -- _1,
   Pinconfigurations.2:iter-star -- _1,
   PinDef                        -- _1 _2 _3 _4 _5,
   PinDef.5:iter-star            -- _1,
   PinName                       -- _1,
   PinRef                        -- _1,
   StateName                     -- _1,
   VarRef                        -- _1,
   Aliases                       -- V  [V vs=2 [KW["aliases:"] _1] _2],
   Aliases.1:iter-star           -- _1,
   Aliases.2:iter-star           -- _1,
   Alias                         -- _1 KW["alias"] _2 KW["("] _3 KW["):"] _4 _5,
   Alias.3:iter-star             -- _1,
   Alias.4:iter-star             -- _1,
   Alias.5:iter-star             -- _1,
   Externals                     -- V  [V vs=2 [KW["external functions:"] _1] _2],
   Externals.1:iter-star         -- _1,
   Externals.2:iter-star         -- _1,
   External                      -- _1 _2 _3,
   External.3:iter-star          -- _1,
   AliasState                    -- _1 KW["state"] _2 _3 _4,
   AliasState.4:iter-star        -- _1,
   PinValueList                  -- V  [V vs=2 [KW["("] _1] KW[")"]],
   PinValueList.1:iter-star      -- _1,
   AliasName                     -- _1,
   Globals                       -- V  [V vs=2 [KW["globals:"] _1] _2],
   Globals.1:iter-star           -- _1,
   Globals.2:iter-star           -- _1,
   Global                        -- _1 _2 _3,
   Global.3:iter-star            -- _1,
   Mode                          -- _1,
   Line                          -- _1 _2,
   Repeat                        -- KW["repeat:"],
   DoOnce                        -- KW["do-once:"],
   Event                         -- KW["event \""] _1 KW["\":"],
   Code                          -- _1 _2,
   Code.2:iter-star              -- _1,
   FuncDecl                      -- _1 _2 _3 KW[":"] _4,
   FuncDecl.3:iter-star          -- _1,
   FuncDecl.4:iter-star          -- _1,
   ParamDecl                     -- _1,
   Codes                         -- _1,
   Codes.1:iter-star             -- _1,
   Emptyline                     -- _1,
   PinValue                      -- _1,
   Switch                        -- KW["switch"] _1,
   AliasStateRef                 -- _1 _2,
   AliasRef                      -- _1
]